import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header/Header";
import ScrollingMessages from "@/components/ScrollingMessages";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {/* App Layout */}
          <div className="h-screen flex flex-col relative overflow-hidden ">
            {/* Header (fixed, no scroll) */}
            <div className="shrink-0 shadow-md dark:shadow-white/10">
              <Header />
              <ScrollingMessages
                messages={[
                  "Restaurant is closed. Nova Delivers will reopen at 5:00 pm",
                  "New menu available tomorrow!",
                  "Free delivery on orders over $50",
                ]}
                duration={20} // optional, seconds per message
              />


            </div>

            {/* Page content (scrollable) */}
            <main className="flex-1 overflow-y-auto hide-scrollbar max-w-7xl mx-auto p-4 w-full">
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
